apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: denyuma/myexample:latest
      ports:
      - containerPort: 80
      resources:
        limits:
          memory: 1024Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"