apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: š©•ª‚ÌDockerIDš/myexample
      ports:
      - containerPort: 80
  imagePullSecrets:
      - name: mysecret